import Head from "next/head";
import { motion } from "framer-motion";

import { Button } from "@/components/ui/button";
import { galada, playfairDisplay, poppins } from "@/utils/fonts";
import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import { getPersonalityData } from "@/data";

export function getServerSideProps(context: GetServerSidePropsContext) {
  const param = context.params?.personality;
  const personality = param as string;

  return {
    props: {
      personality: personality,
    },
  };
}

export const PersonalityPage: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ personality }) => {
  const variants = {
    inView: {
      opacity: 1,
      y: 0,
      transition: { staggerChildren: 0.2, delayChildren: 0.2, duration: 0.8 },
    },
    notInView: {
      opacity: 0,
      y: 100,
      transition: { staggerChildren: 0.05, staggerDirection: -1 },
    },
  };

  const personalityData = getPersonalityData(personality);

  const text = `In the film, Jake Sully demonstrates a profound sense of empathy and intuition, key characteristics of an INFJ. His ability to connect with the Na'vi on a deep emotional level goes beyond mere observation; he truly understands and resonates with their values and way of life. This intuitive connection becomes the driving force behind his decisions.
  
  As an INFJ, Jake is guided by a strong moral compass and a vision
  for a harmonious coexistence between humans and the Na'vi. Despite
  external pressures and conflicting interests, he consistently
  chooses paths that align with his ideals of understanding,
  cooperation, and respect for the environment. His commitment to
  these values is evident in his pivotal decision to stand against
  the destructive actions of some humans, even when it puts him at
  odds with his own kind.

  Jake's internal struggles and moments of introspection further
  reflect INFJ traits. His deep reflections on identity, belonging,
  and the consequences of his choices showcase the complex inner
  world that characterizes this personality type.

  In summary, by attributing an INFJ personality to Jake Sully, we
  highlight his empathetic nature, intuitive understanding,
  commitment to values, and a vision for a better, more harmonious
  world – all of which align with the core characteristics of the
  INFJ type.`;

  return (
    <>
      <Head>
        <title>{personality.toLocaleUpperCase()}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen bg-primary">
        <div className="flex h-[95vh] items-center justify-center">
          <motion.img
            src={personalityData?.image}
            alt={personalityData?.name}
            className="h-full w-[80%] cursor-grab rounded-xl object-cover active:cursor-grabbing"
            drag
            dragSnapToOrigin
            dragConstraints={{
              top: -50,
              left: -50,
              right: 50,
              bottom: 50,
            }}
            whileDrag={{ scale: 0.8, transition: { duration: 1 } }}
            initial={{ opacity: 0, scale: 1.5 }}
            animate={{ scale: 1, opacity: 1 }}
            whileHover={{
              scale: 0.95,
            }}
            whileTap={{ scale: 0.9, transition: { duration: 1 } }}
            // style={{ opacity: 1 - (scrollYProgress as unknown as number) }}
          />
        </div>

        <motion.div
          initial={{ y: 100 }}
          animate={{
            y: -100,
            transition: {
              duration: 1,
              type: "spring",
              delay: 0.2,
              bounce: 0.4,
            },
          }}
          exit={{ y: 100 }}
          className="min-h-40 w-full rounded-t-full border-t-4 border-secondary bg-primary py-4 text-center text-primary-foreground"
        >
          <h1 className={`${galada.className} text-5xl font-medium`}>
            {personalityData?.name}
          </h1>
          <h2
            className={`${playfairDisplay.className} mt-4 text-xl text-secondary-foreground`}
          >
            {personality.toLocaleUpperCase()}
          </h2>
        </motion.div>
        <motion.div
          initial={{ y: 100 }}
          animate={{ y: -100, transition: { duration: 0.5, delay: 0.2 } }}
          exit={{ y: 100 }}
          className="min-h-40 overflow-x-hidden bg-primary px-4 py-4 md:px-8"
        >
          <motion.div
            variants={variants}
            initial={"notInView"}
            whileInView={"inView"}
            className="rounded-2xl border bg-secondary p-4"
          >
            <motion.h3
              initial={{ opacity: 0, x: 100 }}
              whileInView={{ opacity: 1, x: 0, transition: { duration: 0.8 } }}
              className={`${playfairDisplay.className} text-xl font-medium text-primary-foreground`}
            >
              The {personalityData?.personality.name}
            </motion.h3>

            <div className="mt-4 ">
              <motion.img
                src={personalityData?.personality.descriptionImage}
                alt={personalityData?.name}
                className="float-left mb-4 mr-4 max-h-[30vh] cursor-grab rounded-xl border-2 object-cover active:cursor-grabbing"
                drag
                dragSnapToOrigin
                dragConstraints={{
                  top: -50,
                  left: -50,
                  right: 50,
                  bottom: 50,
                }}
                whileDrag={{ scale: 0.8, transition: { duration: 1 } }}
                initial={{ opacity: 0, scale: 1.5 }}
                animate={{ scale: 1, opacity: 1 }}
                whileHover={{
                  scale: 0.95,
                }}
                whileTap={{ scale: 0.9, transition: { duration: 1 } }}
                // style={{ opacity: 1 - (scrollYProgress as unknown as number) }}
              />
              <p
                className={`${poppins.className} mt-4 whitespace-pre-wrap text-primary-foreground`}
              >
                {personalityData?.personality.description}
              </p>
            </div>
          </motion.div>

          <motion.div
            variants={variants}
            initial="notInView"
            whileInView="inView"
            className="mt-12 rounded-2xl border bg-secondary p-4"
          >
            <motion.h3
              initial={{ opacity: 0, x: 100 }}
              whileInView={{ opacity: 1, x: 0, transition: { duration: 0.8 } }}
              className={`${playfairDisplay.className} text-xl font-medium text-primary-foreground`}
            >
              Why is {personalityData?.name} a{" "}
              {personalityData?.personality.name}?
            </motion.h3>

            <div className="mt-4">
              <motion.img
                src={personalityData?.personality.characterImage}
                alt={personalityData?.name}
                className="float-left mb-4 mr-4 max-h-[30vh] cursor-grab rounded-xl border-2 object-cover active:cursor-grabbing"
                drag
                dragSnapToOrigin
                dragConstraints={{
                  top: -50,
                  left: -50,
                  right: 50,
                  bottom: 50,
                }}
                whileDrag={{ scale: 0.8, transition: { duration: 1 } }}
                initial={{ opacity: 0, scale: 1.5 }}
                animate={{ scale: 1, opacity: 1 }}
                whileHover={{
                  scale: 0.95,
                }}
                whileTap={{ scale: 0.9, transition: { duration: 1 } }}
              />
              <p
                className={`${poppins.className} mt-4 whitespace-pre-wrap text-primary-foreground`}
              >
                {personalityData?.personality.characterLink}
              </p>
            </div>
          </motion.div>
        </motion.div>
      </main>
    </>
  );
};

export default PersonalityPage;
