import Head from "next/head";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { MBTISelector } from "@/components/mbti-selector";
import { useRouter } from "next/router";

export default function Example() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen bg-primary">Hi There</main>
    </>
  );
}
