import Head from "next/head";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { MBTISelector } from "@/components/mbti-selector";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen">
        {/* Video Background */}
        <video
          className="absolute left-0 top-0 -z-50 h-full w-full object-cover"
          autoPlay
          loop
          muted
        >
          <source src="/trailer.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <div className="z-10 flex h-full items-center justify-center">
          <div className="text-center text-white">
            <h1 className="mb-4 text-4xl font-bold text-secondary">MBTI</h1>
            <div className="flex gap-4">
              <MBTISelector />
              <Button onClick={() => router.push("/example")}>Confirm</Button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
